version: '3'

services:
  nextcloud.local:
    image: nextcloud
    ports:
      - 80:80
    volumes:
      - ./nextcloud-config:/var/www/html/config
      - ./nextcloud-apps:/var/www/html/custom_apps
      - ./nextcloud-data:/var/www/html/data

  collabora.local:
    build: ./collabora-code
    ports:
      - 9980:9980
    environment:
      - domain=nextcloud.local:80
      - username=admin
      - password=admin
